name: tempo-api-test

services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit_test
    ports:
      - target: ${EMAIL_PORT}
        published: "${EMAIL_PORT}"
        host_ip: 127.0.0.1
        protocol: tcp
      - target: ${EMAIL_PORT}
        published: "${EMAIL_PORT}"
        host_ip: "::1"
        protocol: tcp
      - target: ${EMAIL_UI_PORT}
        published: "${EMAIL_UI_PORT}"
        host_ip: 127.0.0.1
        protocol: tcp
      - target: ${EMAIL_UI_PORT}
        published: "${EMAIL_UI_PORT}"
        host_ip: "::1"
        protocol: tcp

  redis:
    image: redis
    container_name: redis_test
    ports:
      - target: ${REDIS_PORT}
        published: "${REDIS_PORT}"
        host_ip: 127.0.0.1
        protocol: tcp
      - target: ${REDIS_PORT}
        published: "${REDIS_PORT}"
        host_ip: "::1"
        protocol: tcp

  postgres:
    image: postgres:17
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - target: ${DB_PORT}
        published: "${DB_PORT}"
        host_ip: 127.0.0.1
        protocol: tcp
      - target: ${DB_PORT}
        published: "${DB_PORT}"
        host_ip: "::1"
        protocol: tcp
