name: tempo-api-development

services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - target: ${EMAIL_PORT}
        published: "${EMAIL_PORT}"
        host_ip: 127.0.0.1
        protocol: tcp
      - target: ${EMAIL_PORT}
        published: "${EMAIL_PORT}"
        host_ip: "::1"
        protocol: tcp
      - target: ${EMAIL_UI_PORT}
        published: "${EMAIL_UI_PORT}"
        host_ip: 127.0.0.1
        protocol: tcp
      - target: ${EMAIL_UI_PORT}
        published: "${EMAIL_UI_PORT}"
        host_ip: "::1"
        protocol: tcp

  redis:
    image: redis
    container_name: redis
    ports:
      - target: ${REDIS_PORT}
        published: "${REDIS_PORT}"
        host_ip: 127.0.0.1
        protocol: tcp
      - target: ${REDIS_PORT}
        published: "${REDIS_PORT}"
        host_ip: "::1"
        protocol: tcp

  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    ports:
      - target: ${REDIS_INSIGHT_PORT}
        published: "${REDIS_INSIGHT_PORT}"
        host_ip: 127.0.0.1
        protocol: tcp
      - target: ${REDIS_INSIGHT_PORT}
        published: "${REDIS_INSIGHT_PORT}"
        host_ip: "::1"
        protocol: tcp
    environment:
      RI_REDIS_HOST: ${REDIS_HOST}
      RI_REDIS_PORT: ${REDIS_PORT}
    volumes:
      - redisinsight_data:/db
    depends_on:
      - redis

  postgres:
    image: postgres:17
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - target: ${DB_PORT}
        published: "${DB_PORT}"
        host_ip: 127.0.0.1
        protocol: tcp
      - target: ${DB_PORT}
        published: "${DB_PORT}"
        host_ip: "::1"
        protocol: tcp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-${DB_PASSWORD}}
    # chmod 600 means only the owner of the file has read/write access
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass
    ports:
      - target: 80
        published: "${DB_PGADMIN_PORT}"
        host_ip: 127.0.0.1
        protocol: tcp
      - target: 80
        published: "${DB_PGADMIN_PORT}"
        host_ip: "::1"
        protocol: tcp
    depends_on:
      - postgres


volumes:
  postgres_data:
    driver: local
  redisinsight_data:
    driver: local

# automatically connects pgadmin to the database server on startup
configs:
  pgpass:
    content: postgres:${DB_PORT}:*:${DB_USERNAME}:${DB_PASSWORD}
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "${DB_NAME}",
        "Host": "postgres",
        "Port": ${DB_PORT},
        "MaintenanceDB": "${DB_NAME}",
        "Username": "${DB_USERNAME}",
        "Password": "${DB_PASSWORD}",
        "SSLMode": "prefer"
      }}}