export type Currency = {
	code: string;
	name: string;
	symbol: string;
	regionCode: string;
};

export const CURRENCIES: Currency[] = [
	{code: 'AED', name: 'United Arab Emirates dirham', symbol: 'د.إ', regionCode: 'AE'},
	{code: 'AFN', name: 'Afghan afghani', symbol: '؋', regionCode: 'AF'},
	{code: 'ALL', name: 'Albanian lek', symbol: 'L', regionCode: 'AL'},
	{code: 'AMD', name: 'Armenian dram', symbol: '֏', regionCode: 'AM'},
	{code: 'ANG', name: 'Netherlands Antillean guilder', symbol: 'ƒ', regionCode: 'CW'},
	{code: 'AOA', name: 'Angolan kwanza', symbol: 'Kz', regionCode: 'AO'},
	{code: 'ARS', name: 'Argentine peso', symbol: '$', regionCode: 'AR'},
	{code: 'AUD', name: 'Australian dollar', symbol: '$', regionCode: 'AU'},
	{code: 'AWG', name: 'Aruban florin', symbol: 'ƒ', regionCode: 'AW'},
	{code: 'AZN', name: 'Azerbaijani manat', symbol: '₼', regionCode: 'AZ'},
	{code: 'BAM', name: 'Bosnia and Herzegovina convertible mark', symbol: 'KM', regionCode: 'BA'},
	{code: 'BBD', name: 'Barbadian dollar', symbol: '$', regionCode: 'BB'},
	{code: 'BDT', name: 'Bangladeshi taka', symbol: '৳', regionCode: 'BD'},
	{code: 'BGN', name: 'Bulgarian lev', symbol: 'лв', regionCode: 'BG'},
	{code: 'BHD', name: 'Bahraini dinar', symbol: '.د.ب', regionCode: 'BH'},
	{code: 'BIF', name: 'Burundian franc', symbol: 'Fr', regionCode: 'BI'},
	{code: 'BMD', name: 'Bermudian dollar', symbol: '$', regionCode: 'BM'},
	{code: 'BND', name: 'Brunei dollar', symbol: '$', regionCode: 'BN'},
	{code: 'BOB', name: 'Bolivian boliviano', symbol: 'Bs.', regionCode: 'BO'},
	{code: 'BRL', name: 'Brazilian real', symbol: 'R$', regionCode: 'BR'},
	{code: 'BSD', name: 'Bahamian dollar', symbol: '$', regionCode: 'BS'},
	{code: 'BTN', name: 'Bhutanese ngultrum', symbol: 'Nu.', regionCode: 'BT'},
	{code: 'BWP', name: 'Botswana pula', symbol: 'P', regionCode: 'BW'},
	{code: 'BYN', name: 'Belarusian ruble', symbol: 'Br', regionCode: 'BY'},
	{code: 'BZD', name: 'Belize dollar', symbol: '$', regionCode: 'BZ'},
	{code: 'CAD', name: 'Canadian dollar', symbol: '$', regionCode: 'CA'},
	{code: 'CDF', name: 'Congolese franc', symbol: 'FC', regionCode: 'CD'},
	{code: 'CHF', name: 'Swiss franc', symbol: 'Fr.', regionCode: 'CH'},
	{code: 'CKD', name: 'Cook Islands dollar', symbol: '$', regionCode: 'CK'},
	{code: 'CLP', name: 'Chilean peso', symbol: '$', regionCode: 'CL'},
	{code: 'CNY', name: 'Chinese yuan', symbol: '¥', regionCode: 'CN'},
	{code: 'COP', name: 'Colombian peso', symbol: '$', regionCode: 'CO'},
	{code: 'CRC', name: 'Costa Rican colón', symbol: '₡', regionCode: 'CR'},
	{code: 'CUC', name: 'Cuban convertible peso', symbol: '$', regionCode: 'CU'},
	{code: 'CUP', name: 'Cuban peso', symbol: '$', regionCode: 'CU'},
	{code: 'CVE', name: 'Cape Verdean escudo', symbol: 'Esc', regionCode: 'CV'},
	{code: 'CZK', name: 'Czech koruna', symbol: 'Kč', regionCode: 'CZ'},
	{code: 'DJF', name: 'Djiboutian franc', symbol: 'Fr', regionCode: 'DJ'},
	{code: 'DKK', name: 'Danish krone', symbol: 'kr', regionCode: 'DK'},
	{code: 'DOP', name: 'Dominican peso', symbol: '$', regionCode: 'DO'},
	{code: 'DZD', name: 'Algerian dinar', symbol: 'دج', regionCode: 'DZ'},
	{code: 'EGP', name: 'Egyptian pound', symbol: 'E£', regionCode: 'EG'},
	{code: 'ERN', name: 'Eritrean nakfa', symbol: 'Nfk', regionCode: 'ER'},
	{code: 'ETB', name: 'Ethiopian birr', symbol: 'Br', regionCode: 'ET'},
	{code: 'EUR', name: 'Euro', symbol: '€', regionCode: 'EU'},
	{code: 'FJD', name: 'Fijian dollar', symbol: '$', regionCode: 'FJ'},
	{code: 'FKP', name: 'Falkland Islands pound', symbol: '£', regionCode: 'FK'},
	{code: 'FOK', name: 'Faroese króna', symbol: 'kr', regionCode: 'FO'},
	{code: 'GBP', name: 'British pound', symbol: '£', regionCode: 'GB'},
	{code: 'GEL', name: 'lari', symbol: '₾', regionCode: 'GE'},
	{code: 'GGP', name: 'Guernsey pound', symbol: '£', regionCode: 'GG'},
	{code: 'GHS', name: 'Ghanaian cedi', symbol: '₵', regionCode: 'GH'},
	{code: 'GIP', name: 'Gibraltar pound', symbol: '£', regionCode: 'GI'},
	{code: 'GMD', name: 'dalasi', symbol: 'D', regionCode: 'GM'},
	{code: 'GNF', name: 'Guinean franc', symbol: 'Fr', regionCode: 'GN'},
	{code: 'GTQ', name: 'Guatemalan quetzal', symbol: 'Q', regionCode: 'GT'},
	{code: 'GYD', name: 'Guyanese dollar', symbol: '$', regionCode: 'GY'},
	{code: 'HKD', name: 'Hong Kong dollar', symbol: '$', regionCode: 'HK'},
	{code: 'HNL', name: 'Honduran lempira', symbol: 'L', regionCode: 'HN'},
	{code: 'HTG', name: 'Haitian gourde', symbol: 'G', regionCode: 'HT'},
	{code: 'HUF', name: 'Hungarian forint', symbol: 'Ft', regionCode: 'HU'},
	{code: 'IDR', name: 'Indonesian rupiah', symbol: 'Rp', regionCode: 'ID'},
	{code: 'ILS', name: 'Israeli new shekel', symbol: '₪', regionCode: 'IL'},
	{code: 'IMP', name: 'Manx pound', symbol: '£', regionCode: 'IM'},
	{code: 'INR', name: 'Indian rupee', symbol: '₹', regionCode: 'IN'},
	{code: 'IQD', name: 'Iraqi dinar', symbol: 'ع.د', regionCode: 'IQ'},
	{code: 'IRR', name: 'Iranian rial', symbol: '﷼', regionCode: 'IR'},
	{code: 'ISK', name: 'Icelandic króna', symbol: 'kr', regionCode: 'IS'},
	{code: 'JEP', name: 'Jersey pound', symbol: '£', regionCode: 'JE'},
	{code: 'JMD', name: 'Jamaican dollar', symbol: '$', regionCode: 'JM'},
	{code: 'JOD', name: 'Jordanian dinar', symbol: 'JD', regionCode: 'JO'},
	{code: 'JPY', name: 'Japanese yen', symbol: '¥', regionCode: 'JP'},
	{code: 'KES', name: 'Kenyan shilling', symbol: 'Sh', regionCode: 'KE'},
	{code: 'KGS', name: 'Kyrgyzstani som', symbol: 'с', regionCode: 'KG'},
	{code: 'KHR', name: 'Cambodian riel', symbol: '៛', regionCode: 'KH'},
	{code: 'KID', name: 'Kiribati dollar', symbol: '$', regionCode: 'KI'},
	{code: 'KMF', name: 'Comorian franc', symbol: 'Fr', regionCode: 'KM'},
	{code: 'KPW', name: 'North Korean won', symbol: '₩', regionCode: 'KP'},
	{code: 'KRW', name: 'South Korean won', symbol: '₩', regionCode: 'KR'},
	{code: 'KWD', name: 'Kuwaiti dinar', symbol: 'د.ك', regionCode: 'KW'},
	{code: 'KYD', name: 'Cayman Islands dollar', symbol: '$', regionCode: 'KY'},
	{code: 'KZT', name: 'Kazakhstani tenge', symbol: '₸', regionCode: 'KZ'},
	{code: 'LAK', name: 'Lao kip', symbol: '₭', regionCode: 'LA'},
	{code: 'LBP', name: 'Lebanese pound', symbol: 'ل.ل', regionCode: 'LB'},
	{code: 'LKR', name: 'Sri Lankan rupee', symbol: 'Rs  රු', regionCode: 'LK'},
	{code: 'LRD', name: 'Liberian dollar', symbol: '$', regionCode: 'LR'},
	{code: 'LSL', name: 'Lesotho loti', symbol: 'L', regionCode: 'LS'},
	{code: 'LYD', name: 'Libyan dinar', symbol: 'ل.د', regionCode: 'LY'},
	{code: 'MAD', name: 'Moroccan dirham', symbol: 'DH', regionCode: 'MA'},
	{code: 'MDL', name: 'Moldovan leu', symbol: 'L', regionCode: 'MD'},
	{code: 'MGA', name: 'Malagasy ariary', symbol: 'Ar', regionCode: 'MG'},
	{code: 'MKD', name: 'denar', symbol: 'den', regionCode: 'MK'},
	{code: 'MMK', name: 'Burmese kyat', symbol: 'Ks', regionCode: 'MM'},
	{code: 'MNT', name: 'Mongolian tögrög', symbol: '₮', regionCode: 'MN'},
	{code: 'MOP', name: 'Macanese pataca', symbol: 'P', regionCode: 'MO'},
	{code: 'MRU', name: 'Mauritanian ouguiya', symbol: 'UM', regionCode: 'MR'},
	{code: 'MUR', name: 'Mauritian rupee', symbol: '₨', regionCode: 'MU'},
	{code: 'MVR', name: 'Maldivian rufiyaa', symbol: '.ރ', regionCode: 'MV'},
	{code: 'MWK', name: 'Malawian kwacha', symbol: 'MK', regionCode: 'MW'},
	{code: 'MXN', name: 'Mexican peso', symbol: '$', regionCode: 'MX'},
	{code: 'MYR', name: 'Malaysian ringgit', symbol: 'RM', regionCode: 'MY'},
	{code: 'MZN', name: 'Mozambican metical', symbol: 'MT', regionCode: 'MZ'},
	{code: 'NAD', name: 'Namibian dollar', symbol: '$', regionCode: 'NA'},
	{code: 'NGN', name: 'Nigerian naira', symbol: '₦', regionCode: 'NG'},
	{code: 'NIO', name: 'Nicaraguan córdoba', symbol: 'C$', regionCode: 'NI'},
	{code: 'NOK', name: 'krone', symbol: 'kr', regionCode: 'NO'},
	{code: 'NPR', name: 'Nepalese rupee', symbol: '₨', regionCode: 'NP'},
	{code: 'NZD', name: 'New Zealand dollar', symbol: '$', regionCode: 'NZ'},
	{code: 'OMR', name: 'Omani rial', symbol: 'ر.ع.', regionCode: 'OM'},
	{code: 'PAB', name: 'Panamanian balboa', symbol: 'B/.', regionCode: 'PA'},
	{code: 'PEN', name: 'Peruvian sol', symbol: 'S/ ', regionCode: 'PE'},
	{code: 'PGK', name: 'Papua New Guinean kina', symbol: 'K', regionCode: 'PG'},
	{code: 'PHP', name: 'Philippine peso', symbol: '₱', regionCode: 'PH'},
	{code: 'PKR', name: 'Pakistani rupee', symbol: '₨', regionCode: 'PK'},
	{code: 'PLN', name: 'Polish złoty', symbol: 'zł', regionCode: 'PL'},
	{code: 'PYG', name: 'Paraguayan guaraní', symbol: '₲', regionCode: 'PY'},
	{code: 'QAR', name: 'Qatari riyal', symbol: 'ر.ق', regionCode: 'QA'},
	{code: 'RON', name: 'Romanian leu', symbol: 'lei', regionCode: 'RO'},
	{code: 'RSD', name: 'Serbian dinar', symbol: 'дин.', regionCode: 'RS'},
	{code: 'RUB', name: 'Russian ruble', symbol: '₽', regionCode: 'RU'},
	{code: 'RWF', name: 'Rwandan franc', symbol: 'Fr', regionCode: 'RW'},
	{code: 'SAR', name: 'Saudi riyal', symbol: 'ر.س', regionCode: 'SA'},
	{code: 'SBD', name: 'Solomon Islands dollar', symbol: '$', regionCode: 'SB'},
	{code: 'SCR', name: 'Seychellois rupee', symbol: '₨', regionCode: 'SC'},
	{code: 'SDG', name: 'Sudanese pound', symbol: 'ج.س', regionCode: 'SD'},
	{code: 'SEK', name: 'Swedish krona', symbol: 'kr', regionCode: 'SE'},
	{code: 'SGD', name: 'Singapore dollar', symbol: '$', regionCode: 'SG'},
	{code: 'SHP', name: 'Saint Helena pound', symbol: '£', regionCode: 'SH'},
	{code: 'SLE', name: 'Leone', symbol: 'Le', regionCode: 'SL'},
	{code: 'SOS', name: 'Somali shilling', symbol: 'Sh', regionCode: 'SO'},
	{code: 'SRD', name: 'Surinamese dollar', symbol: '$', regionCode: 'SR'},
	{code: 'SSP', name: 'South Sudanese pound', symbol: '£', regionCode: 'SS'},
	{code: 'STN', name: 'São Tomé and Príncipe dobra', symbol: 'Db', regionCode: 'ST'},
	{code: 'SYP', name: 'Syrian pound', symbol: '£', regionCode: 'SY'},
	{code: 'SZL', name: 'Swazi lilangeni', symbol: 'L', regionCode: 'SZ'},
	{code: 'THB', name: 'Thai baht', symbol: '฿', regionCode: 'TH'},
	{code: 'TJS', name: 'Tajikistani somoni', symbol: 'ЅМ', regionCode: 'TJ'},
	{code: 'TMT', name: 'Turkmenistan manat', symbol: 'm', regionCode: 'TM'},
	{code: 'TND', name: 'Tunisian dinar', symbol: 'د.ت', regionCode: 'TN'},
	{code: 'TOP', name: 'Tongan paʻanga', symbol: 'T$', regionCode: 'TO'},
	{code: 'TRY', name: 'Turkish lira', symbol: '₺', regionCode: 'TR'},
	{code: 'TTD', name: 'Trinidad and Tobago dollar', symbol: '$', regionCode: 'TT'},
	{code: 'TVD', name: 'Tuvaluan dollar', symbol: '$', regionCode: 'TV'},
	{code: 'TWD', name: 'New Taiwan dollar', symbol: '$', regionCode: 'TW'},
	{code: 'TZS', name: 'Tanzanian shilling', symbol: 'Sh', regionCode: 'TZ'},
	{code: 'UAH', name: 'Ukrainian hryvnia', symbol: '₴', regionCode: 'UA'},
	{code: 'UGX', name: 'Ugandan shilling', symbol: 'Sh', regionCode: 'UG'},
	{code: 'USD', name: 'United States dollar', symbol: '$', regionCode: 'US'},
	{code: 'UYU', name: 'Uruguayan peso', symbol: '$', regionCode: 'UY'},
	{code: 'UZS', name: 'Uzbekistani soʻm', symbol: "so'm", regionCode: 'UZ'},
	{code: 'VES', name: 'Venezuelan bolívar soberano', symbol: 'Bs.S.', regionCode: 'VE'},
	{code: 'VND', name: 'Vietnamese đồng', symbol: '₫', regionCode: 'VN'},
	{code: 'VUV', name: 'Vanuatu vatu', symbol: 'Vt', regionCode: 'VU'},
	{code: 'WST', name: 'Samoan tālā', symbol: 'T', regionCode: 'WS'},
	{code: 'XAF', name: 'Central African CFA franc', symbol: 'Fr', regionCode: 'CM'},
	{code: 'XCD', name: 'Eastern Caribbean dollar', symbol: '$', regionCode: 'KN'},
	{code: 'XOF', name: 'West African CFA franc', symbol: 'Fr', regionCode: 'SN'},
	{code: 'XPF', name: 'CFP franc', symbol: '₣', regionCode: 'PF'},
	{code: 'YER', name: 'Yemeni rial', symbol: '﷼', regionCode: 'YE'},
	{code: 'ZAR', name: 'South African rand', symbol: 'R', regionCode: 'ZA'},
	{code: 'ZMW', name: 'Zambian kwacha', symbol: 'ZK', regionCode: 'ZM'},
	{code: 'ZWL', name: 'Zimbabwean dollar', symbol: '$', regionCode: 'ZW'},
];

export const CURRENCY_CODES = CURRENCIES.map((currency) => currency.code);
