export const BANK_TRANSACTION_TYPES = {
	CARD_PAYMENT: 'CARD_PAYMENT',
	TRANSFER: 'TRANSFER',
	DIRECT_DEBIT: 'DIRECT_DEBIT',
	CASH_WITHDRAWAL: 'CASH_WITHDRAWAL',
	FEE: 'FEE',
	INTEREST: 'INTEREST',
	SALARY: 'SALARY',
	REFUND: 'REFUND',
	OTHER: 'OTHER',
} as const;

export type BankTransactionType = (typeof BANK_TRANSACTION_TYPES)[keyof typeof BANK_TRANSACTION_TYPES];

type BankTransactionClassification = {
	code?: string;
	subCode?: string;
	description?: string;
};

const STRUCTURED_CODE_TYPES: Record<string, BankTransactionType> = {
	CARD: BANK_TRANSACTION_TYPES.CARD_PAYMENT,
	CARD_PAYMENT: BANK_TRANSACTION_TYPES.CARD_PAYMENT,
	CCRD: BANK_TRANSACTION_TYPES.CARD_PAYMENT,
	POS: BANK_TRANSACTION_TYPES.CARD_PAYMENT,
	POSD: BANK_TRANSACTION_TYPES.CARD_PAYMENT,
	TRANSFER: BANK_TRANSACTION_TYPES.TRANSFER,
	TRF: BANK_TRANSACTION_TYPES.TRANSFER,
	ESCT: BANK_TRANSACTION_TYPES.TRANSFER,
	ICDT: BANK_TRANSACTION_TYPES.TRANSFER,
	ITRF: BANK_TRANSACTION_TYPES.TRANSFER,
	RCDT: BANK_TRANSACTION_TYPES.TRANSFER,
	DIRECT_DEBIT: BANK_TRANSACTION_TYPES.DIRECT_DEBIT,
	DD: BANK_TRANSACTION_TYPES.DIRECT_DEBIT,
	IDDT: BANK_TRANSACTION_TYPES.DIRECT_DEBIT,
	RDDT: BANK_TRANSACTION_TYPES.DIRECT_DEBIT,
	FEE: BANK_TRANSACTION_TYPES.FEE,
	CHRG: BANK_TRANSACTION_TYPES.FEE,
	COMM: BANK_TRANSACTION_TYPES.FEE,
	COME: BANK_TRANSACTION_TYPES.FEE,
	INTEREST: BANK_TRANSACTION_TYPES.INTEREST,
	INT: BANK_TRANSACTION_TYPES.INTEREST,
	INTR: BANK_TRANSACTION_TYPES.INTEREST,
	SALARY: BANK_TRANSACTION_TYPES.SALARY,
	SALA: BANK_TRANSACTION_TYPES.SALARY,
	REFUND: BANK_TRANSACTION_TYPES.REFUND,
	RIMB: BANK_TRANSACTION_TYPES.REFUND,
	CASH_WITHDRAWAL: BANK_TRANSACTION_TYPES.CASH_WITHDRAWAL,
	ATM: BANK_TRANSACTION_TYPES.CASH_WITHDRAWAL,
	CWDL: BANK_TRANSACTION_TYPES.CASH_WITHDRAWAL,
	WITHDRAWAL: BANK_TRANSACTION_TYPES.CASH_WITHDRAWAL,
};

// Only structured provider codes are trusted for deterministic transaction-type inference.

export function normalizeBankTransactionType({code, subCode}: BankTransactionClassification): BankTransactionType {
	const structuredType = [subCode, code]
		.map((value) => value?.trim().toUpperCase())
		.map((value) => (value ? STRUCTURED_CODE_TYPES[value] : undefined))
		.find((type): type is BankTransactionType => type !== undefined);
	return structuredType ?? BANK_TRANSACTION_TYPES.OTHER;
}
