export const BANK_SYNC_STATUSES = {
	IDLE: 'IDLE',
	QUEUED: 'QUEUED',
	RUNNING: 'RUNNING',
	SUCCEEDED: 'SUCCEEDED',
	PARTIAL: 'PARTIAL',
	FAILED: 'FAILED',
	RATE_LIMITED: 'RATE_LIMITED',
	EXPIRED: 'EXPIRED',
} as const;

export type BankSyncStatus = (typeof BANK_SYNC_STATUSES)[keyof typeof BANK_SYNC_STATUSES];

export const BANKING_DEFAULT_RETRY_AFTER_SECONDS = 6 * 60 * 60;
export const BANKING_MAX_RETRY_AFTER_SECONDS = 8_000_000_000_000;
export const BANKING_TRANSIENT_RETRY_BASE_MS = 15 * 60 * 1000;
