export const BANK_TRANSACTION_CATEGORIZATION_PROMPT_VERSION = 'bank-transaction-categorization-v1';
export const BANK_TRANSACTION_CATEGORIZATION_PROVIDER_NAME = 'openai';
export const BANK_TRANSACTION_CATEGORIZATION_REQUEST_TIMEOUT_MS = 30_000;
